// src/app/layout.js
import ClientSessionProvider from '@/components/ClientSessionProvider';
import './globals.css';

export const metadata = {
  title: 'CATC Travel Agency',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientSessionProvider>
          {children}
        </ClientSessionProvider>
      </body>
    </html>
  );
}